[package]
name = "rusttyc"
version = "0.2.0"
authors = ["Maximilian Schwenger <schwenger@react.uni-saarland.de>"]
edition = "2018"

[dependencies]
ena = "0.13.0" # union-find implementation

[[example]]
name = "parametrized_function"